package com.tstmodern.registry.machine;

import java.util.Arrays;
import java.util.stream.Collectors;

/** Exact mechanical transpose of the TST Disassembler's 23 by 28 source matrix. */
public final class DisassemblerStructure {
    public static final int WIDTH = 27;
    public static final int HEIGHT = 23;
    public static final int DEPTH = 28;

    public static final String[][] AISLES = {
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            III            ",
            "            I~I            ",
            "            III            "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            GCG            ",
            "             G             ",
            "             G             "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            GCG            ",
            "            JGJ            ",
            "     G      J J      G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "           D   D           ",
            "           D   D           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            GCG            ",
            "     J       G       J     ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "           D   D           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            GCG            ",
            "     J      JGJ      J     ",
            "     G      J J      G     ",
            "     G      J J      G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "           D   D           ",
            "           D   D           ",
            "                           ",
            "            GHG            ",
            "     J       G       J     ",
            "     G               G     ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            EEE            ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "           DGHGD           ",
            "     J      JGJ      J     ",
            "     G      J J      G     ",
            "            J J            ",
            "            J J            ",
            "     G      J J      G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            FFF            ",
            "          EEBBBEE          ",
            "            FFF            ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "             H             ",
            "     J      GGG      J     ",
            "     G     D   D     G     ",
            "                           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "          FF   FF          ",
            "         EBBABABBE         ",
            "          FF   FF          ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                 F         ",
            "          AA B AABE        ",
            "                 F         ",
            "                           ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                  F        ",
            "             B   ABE       ",
            "                  F        ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "                           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                  F        ",
            "                 ABE       ",
            "                  F        ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "           D   D           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            FFF            ",
            "          FF   FF          ",
            "         F                 ",
            "        F                  ",
            "        F                  ",
            "       F           F       ",
            "     GEF          ABEG     ",
            "       F           F       ",
            "     J  F            J     ",
            "     G  F            G     ",
            "         F                 ",
            "          FF   FF          ",
            "            FFF            ",
            "                           ",
            "                           ",
            "                           ",
            "           D   D           ",
            "                           ",
            "     G               G     "
        },
        {
            "           D   D           ",
            "                           ",
            "                           ",
            "            EEE            ",
            "          EEBBBEE          ",
            "         EBBABABBE         ",
            "        EBAA B AA          ",
            "       EBA   B             ",
            "       EBA                 ",
            "     GEBA          FEG     ",
            "     GBBBBB  H  BBBBBG     ",
            "     GEBA          FEG     ",
            "     G EBA           G     ",
            "     G EBA   B       G     ",
            "     G  EBAA B AA    G     ",
            "     G   EBBABABBE   G     ",
            "     G    EEBBBEE    G     ",
            "     G      EEE      G     ",
            "    JG               GJ    ",
            "   JGGJ             JGGJ   ",
            "  JG GGJ   D   D   JGG GJ  ",
            " JG  G GJ         JG G  GJ ",
            "GGGGGGGGGGGGGGGGGGGGGGGGGGG"
        },
        {
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "            FFF            ",
            "          FF   FF          ",
            "         F                 ",
            "        F                  ",
            "        F                  ",
            "       F           F       ",
            "     GEF          ABEG     ",
            "       F           F       ",
            "     J  F            J     ",
            "     G  F            G     ",
            "         F                 ",
            "          FF   FF          ",
            "            FFF            ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                  F        ",
            "                 ABE       ",
            "                  F        ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                  F        ",
            "             B   ABE       ",
            "                  F        ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                 F         ",
            "          AA B AABE        ",
            "                 F         ",
            "                           ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "          FF   FF          ",
            "         EBBABABBE         ",
            "          FF   FF          ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "           D G D           ",
            "            GGG            ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            FFF            ",
            "          EEBBBEE          ",
            "            FFF            ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "                           ",
            "     G               G     "
        },
        {
            "                           ",
            "                           ",
            "            GGG            ",
            "           DGGGD           ",
            "            GGG            ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            EEE            ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "                           ",
            "                           ",
            "     G      GGG      G     "
        },
        {
            "                           ",
            "                           ",
            "             G             ",
            "            GGG            ",
            "           DGGGD           ",
            "           D G D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     J               J     ",
            "     G               G     ",
            "            J J            ",
            "     G      GGG      G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "             G             ",
            "            GGG            ",
            "            GGG            ",
            "           D G D           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "     J      J J      J     ",
            "     G               G     ",
            "     G      GGG      G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "             G             ",
            "            GGG            ",
            "            GGG            ",
            "             G             ",
            "           D   D           ",
            "           D   D           ",
            "           D   D           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            J J            ",
            "                           ",
            "     J       G       J     ",
            "     G      GGG      G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "             G             ",
            "            GGG            ",
            "            GGG            ",
            "             G             ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "            J J            ",
            "                           ",
            "             G             ",
            "             G             ",
            "     G      GGG      G     "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "             G             ",
            "            GGG            ",
            "            GGG            ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "            JGJ            ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "            GGG            "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "             G             ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            ",
            "            GGG            "
        },
        {
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "                           ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "             G             ",
            "            GGG            "
        }
    };

    private DisassemblerStructure() {}

    static String normalizedRows() {
        return Arrays.stream(AISLES).flatMap(Arrays::stream).collect(Collectors.joining("\n"));
    }
}
