package com.tstmodern.registry.machine;

/** Exact TST source layers transposed to GTCEu aisles: [back][down][right]. */
public final class IncompactCyclotronStructure {
    public static final int WIDTH = 47;
    public static final int HEIGHT = 7;
    public static final int DEPTH = 47;
    public static final int CONTROLLER_RIGHT = 23;
    public static final int CONTROLLER_DOWN = 3;
    public static final int CONTROLLER_BACK = 40;

    private static final String[][] SOURCE_LAYERS = {
            {"                                               ","                                               ","                    BDDDDDB                    ","                    BDEAEDB                    ","                    BDDDDDB                    ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","  BBB                                     BBB  ","  DDD                                     DDD  ","  DED                                     DED  ","  DAD                                     DAD  ","  DED                                     DED  ","  DDD                                     DDD  ","  BBB                                     BBB  ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                    BDDDDDB                    ","                    BDEAEDB                    ","                    BDDDDDB                    ","                                               ","                                               "},
            {"                                               ","                    BDEAEDB                    ","                   DD     DD                   ","                DDDDD     DDDDD                ","              DDDDDDD     DDDDDDD              ","            DDDDDDD BDEAEDB DDDDDDD            ","           DDDDD               DDDDD           ","          DDDD                   DDDD          ","         DDD                       DDD         ","        DDD                         DDD        ","       DDD                           DDD       ","      DDD                             DDD      ","     DDD                               DDD     ","     DDD                               DDD     ","    DDD                                 DDD    ","    DDD                                 DDD    ","   DDD                                   DDD   ","   DDD                                   DDD   ","   DDD                                   DDD   ","  DDD                                     DDD  "," BDDDB                                   BDDDB "," D   D                                   D   D "," E   E                                   E   E "," A   A                                   A   A "," E   E                                   E   E "," D   D                                   D   D "," BDDDB                                   BDDDB ","  DDD                                     DDD  ","   DDD                                   DDD   ","   DDD                                   DDD   ","   DDD                                   DDD   ","    DDD                                 DDD    ","    DDD                                 DDD    ","     DDD                               DDD     ","     DDD                               DDD     ","      DDD                             DDD      ","       DDD                           DDD       ","        DDD                         DDD        ","         DDD                       DDD         ","          DDDD                   DDDD          ","           DDDDD               DDDDD           ","            DDDDDDD BDEAEDB DDDDDDD            ","              DDDDDDD     DDDDDDD              ","                DDDDD     DDDDD                ","                   DD     DD                   ","                    BDEAEDB                    ","                                               "},
            {"                    BDDDDDB                    ","                   DD     DD                   ","                DDDDD     DDDDD                ","              DDDDDCCCCCCCCCDDDDD              ","            DDDDCCCDD     DDCCCDDDD            ","           DDDCCDDDDD     DDDDDCCDDD           ","          FDCCDDDDD BDDDDDB DDDDDCCDF          ","         DDCDDDD               DDDDCDD         ","        DDCDDD                   DDDCDD        ","       DDCDF                       FDCDD       ","      FDCDD                         DDCDF      ","     DDCDF                           FDCDD     ","    DDCDD                             DDCDD    ","    DDCDD                             DDCDD    ","   DDCDD                               DDCDD   ","   DDCDD                               DDCDD   ","  DDCDD                                 DDCDD  ","  DDCDD                                 DDCDD  ","  DDCDD                                 DDCDD  "," DDCDD                                   DDCDD ","BDDCDDB                                 BDDCDDB","D  C  D                                 D  C  D","D  C  D                                 D  C  D","D  C  D                                 D  C  D","D  C  D                                 D  C  D","D  C  D                                 D  C  D","BDDCDDB                                 BDDCDDB"," DDCDD                                   DDCDD ","  DDCDD                                 DDCDD  ","  DDCDD                                 DDCDD  ","  DDCDD                                 DDCDD  ","   DDCDD                               DDCDD   ","   DDCDD                               DDCDD   ","    DDCDD                             DDCDD    ","    DDCDD                             DDCDD    ","     DDCDF                           FDCDD     ","      FDCDD                         DDCDF      ","       DDCDF                       FDCDD       ","        DDCDDD                   DDDCDD        ","         DDCDDDD               DDDDCDD         ","          FDCCDDDDD BDDDDDB DDDDDCCDF          ","           DDDCCDDDDD     DDDDDCCDDD           ","            DDDDCCCDD     DDCCCDDDD            ","              DDDDDCCCCCCCCCDDDDD              ","                DDDDD     DDDDD                ","                   DD     DD                   ","                    BDDDDDB                    "},
            {"                    BDEAEDB                    ","                   DD     DD                   ","                DDDCCCCCCCCCDDD                ","              DDCCCCCCCCCCCCCCCDD              ","            DDCCCCCCCCCCCCCCCCCCCDD            ","           DCCCCCCCDD     DDCCCCCCCD           ","          DCCCCCDDD BDEAEDB DDDCCCCCD          ","         DCCCCDD               DDCCCCD         ","        DCCCDD                   DDCCCD        ","       DCCCD                       DCCCD       ","      DCCCD                         DCCCD      ","     DCCCD                           DCCCD     ","    DCCCD                             DCCCD    ","    DCCCD                             DCCCD    ","   DCCCD                               DCCCD   ","   DCCCD                               DCCCD   ","  DCCCD                                 DCCCD  ","  DCCCD                                 DCCCD  ","  DCCCD                                 DCCCD  "," DCCCD                                   DCCCD ","BDCCCDB                                 BDCCCDB","D CCC D                                 D CCC D","E CCC E                                 E CCC E","A CCC A                                 A CCC A","E CCC E                                 E CCC E","D CCC D                                 D CCC D","BDCCCDB                                 BDCCCDB"," DCCCD                                   DCCCD ","  DCCCD                                 DCCCD  ","  DCCCD                                 DCCCD  ","  DCCCD                                 DCCCD  ","   DCCCD                               DCCCD   ","   DCCCD                               DCCCD   ","    DCCCD                             DCCCD    ","    DCCCD                             DCCCD    ","     DCCCD                           DCCCD     ","      DCCCD                         DCCCD      ","       DCCCD                       DCCCD       ","        DCCCDD                   DDCCCD        ","         DCCCCDD               DDCCCCD         ","          DCCCCCDDD BDE~EDB DDDCCCCCD          ","           DCCCCCCCDD     DDCCCCCCCD           ","            DDCCCCCCCCCCCCCCCCCCCDD            ","              DDCCCCCCCCCCCCCCCDD              ","                DDDCCCCCCCCCDDD                ","                   DD     DD                   ","                    BDEAEDB                    "},
            {"                    BDDDDDB                    ","                   DD     DD                   ","                DDDDD     DDDDD                ","              DDDDDCCCCCCCCCDDDDD              ","            DDDDCCCDD     DDCCCDDDD            ","           DDDCCDDDDD     DDDDDCCDDD           ","          FDCCDDDDD BDDDDDB DDDDDCCDF          ","         DDCDDDD               DDDDCDD         ","        DDCDDD                   DDDCDD        ","       DDCDF                       FDCDD       ","      FDCDD                         DDCDF      ","     DDCDF                           FDCDD     ","    DDCDD                             DDCDD    ","    DDCDD                             DDCDD    ","   DDCDD                               DDCDD   ","   DDCDD                               DDCDD   ","  DDCDD                                 DDCDD  ","  DDCDD                                 DDCDD  ","  DDCDD                                 DDCDD  "," DDCDD                                   DDCDD ","BDDCDDB                                 BDDCDDB","D  C  D                                 D  C  D","D  C  D                                 D  C  D","D  C  D                                 D  C  D","D  C  D                                 D  C  D","D  C  D                                 D  C  D","BDDCDDB                                 BDDCDDB"," DDCDD                                   DDCDD ","  DDCDD                                 DDCDD  ","  DDCDD                                 DDCDD  ","  DDCDD                                 DDCDD  ","   DDCDD                               DDCDD   ","   DDCDD                               DDCDD   ","    DDCDD                             DDCDD    ","    DDCDD                             DDCDD    ","     DDCDF                           FDCDD     ","      FDCDD                         DDCDF      ","       DDCDF                       FDCDD       ","        DDCDDD                   DDDCDD        ","         DDCDDDD               DDDDCDD         ","          FDCCDDDDD BDDDDDB DDDDDCCDF          ","           DDDCCDDDDD     DDDDDCCDDD           ","            DDDDCCCDD     DDCCCDDDD            ","              DDDDDCCCCCCCCCDDDDD              ","                DDDDD     DDDDD                ","                   DD     DD                   ","                    BDDDDDB                    "},
            {"                                               ","                    BDEAEDB                    ","                   DD     DD                   ","                DDDDD     DDDDD                ","              DDDDDDD     DDDDDDD              ","            DDDDDDD BDEAEDB DDDDDDD            ","           DDDDD               DDDDD           ","          DDDD                   DDDD          ","         DDD                       DDD         ","        DDD                         DDD        ","       DDD                           DDD       ","      DDD                             DDD      ","     DDD                               DDD     ","     DDD                               DDD     ","    DDD                                 DDD    ","    DDD                                 DDD    ","   DDD                                   DDD   ","   DDD                                   DDD   ","   DDD                                   DDD   ","  DDD                                     DDD  "," BDDDB                                   BDDDB "," D   D                                   D   D "," E   E                                   E   E "," A   A                                   A   A "," E   E                                   E   E "," D   D                                   D   D "," BDDDB                                   BDDDB ","  DDD                                     DDD  ","   DDD                                   DDD   ","   DDD                                   DDD   ","   DDD                                   DDD   ","    DDD                                 DDD    ","    DDD                                 DDD    ","     DDD                               DDD     ","     DDD                               DDD     ","      DDD                             DDD      ","       DDD                           DDD       ","        DDD                         DDD        ","         DDD                       DDD         ","          DDDD                   DDDD          ","           DDDDD               DDDDD           ","            DDDDDDD BDEAEDB DDDDDDD            ","              DDDDDDD     DDDDDDD              ","                DDDDD     DDDDD                ","                   DD     DD                   ","                    BDEAEDB                    ","                                               "},
            {"                                               ","                                               ","                    BDDDDDB                    ","                    BDEAEDB                    ","                    BDDDDDB                    ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","  BBB                                     BBB  ","  DDD                                     DDD  ","  DED                                     DED  ","  DAD                                     DAD  ","  DED                                     DED  ","  DDD                                     DDD  ","  BBB                                     BBB  ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                                               ","                    BDDDDDB                    ","                    BDEAEDB                    ","                    BDDDDDB                    ","                                               ","                                               "}
    };

    public static final String[][] PATTERN_AISLES = transpose(SOURCE_LAYERS);

    private IncompactCyclotronStructure() {}

    public static char symbolAt(int right, int down, int back) {
        return PATTERN_AISLES[back][down].charAt(right);
    }

    private static String[][] transpose(String[][] layers) {
        String[][] aisles = new String[DEPTH][HEIGHT];
        for (int back = 0; back < aisles.length; back++) {
            for (int down = 0; down < layers.length; down++) {
                aisles[back][down] = layers[down][back];
            }
        }
        return aisles;
    }
}
