package com.tstmodern.registry.machine;

/** Exact TST source layers transposed to GTCEu aisles: [back][down][right]. */
public final class LargeNeutronOscillatorStructure {
    public static final int WIDTH = 23;
    public static final int HEIGHT = 40;
    public static final int DEPTH = 13;
    public static final int CONTROLLER_RIGHT = 3;
    public static final int CONTROLLER_DOWN = 36;
    public static final int CONTROLLER_BACK = 1;

    private static final String[][] SOURCE_LAYERS = {
            {
                "                       ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                "            G       G  ",
                "           GFFFFFFFFFG ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                " CCCCC      G       G  ",
                " CCCCC     GFFFFFFFFFG ",
                " CCCCC      FEFEFEFEF  ",
                " CCCCC      FFFFFFFFF  ",
                " CCCCC      FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                " CAAAC      G       G  ",
                " CDDDC     GFFFFFFFFFG ",
                " CDDDC      FEFEFEFEF  ",
                " CDDDC      FFFFFFFFF  ",
                " CCCCC      FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                " CA~AC      G       G  ",
                " CDDDC     GFFFFFFFFFG ",
                " CDDDC      FEFEFEFEF  ",
                " CDDDC      FFFFFFFFF  ",
                " CCCCC      FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                " CAAAC      G       G  ",
                " CDDDC     GFFFFFFFFFG ",
                " CDDDC      FEFEFEFEF  ",
                " CDDDC      FFFFFFFFF  ",
                " CCCCC      FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "            FFFFFFFFF  ",
                "            FEFEFEFEF  ",
                "           GFFFFFFFFFG ",
                "            G       G  ",
                "                       "
            },
            {
                "                       ",
                " CCCCC     CCCCCCCCCCC ",
                " CCCCCCCCCCCCCCCCCCCCC ",
                " CCCCCCCCCCCCCCCCCCCCC ",
                " CCCCCCCCCCCCCCCCCCCCC ",
                " CCCCC     CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "           CCCCCCCCCCC ",
                "                       "
            },
            {
                "BBBBBBB   BBBBBBBBBBBBB",
                "BBBBBBBBBBBBBBBBBBBBBBB",
                "BBBBBBBBBBBBBBBBBBBBBBB",
                "BBBBBBBBBBBBBBBBBBBBBBB",
                "BBBBBBBBBBBBBBBBBBBBBBB",
                "BBBBBBBBBBBBBBBBBBBBBBB",
                "BBBBBBB   BBBBBBBBBBBBB",
                "          BBBBBBBBBBBBB",
                "          BBBBBBBBBBBBB",
                "          BBBBBBBBBBBBB",
                "          BBBBBBBBBBBBB",
                "          BBBBBBBBBBBBB",
                "          BBBBBBBBBBBBB"
            }
    };

    public static final String[][] PATTERN_AISLES = transpose(SOURCE_LAYERS);

    private LargeNeutronOscillatorStructure() {}

    public static char symbolAt(int right, int down, int back) {
        return PATTERN_AISLES[back][down].charAt(right);
    }

    private static String[][] transpose(String[][] layers) {
        String[][] aisles = new String[DEPTH][HEIGHT];
        for (int back = 0; back < aisles.length; back++) {
            for (int down = 0; down < layers.length; down++) {
                aisles[back][down] = layers[down][back];
            }
        }
        return aisles;
    }
}
